root = "."

[build]
bin = "./bin/server"
cmd = "go build -o ./bin/server"

delay = 20
exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "node_modules",
    "static",
    "api/serverless",
]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "env", "jsx", "css"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = true
